name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: miccy/snake-evolution@v1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
          theme: github-dark

      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: output
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
