name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: miccy/snake-evolution@v1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update contribution snake"
          file_pattern: assets/*.svg
